In [ ]:
import numpy as np
import pandas as pd

: 

In [2]:
data=pd.read_csv('Crop_recommendation.csv')

In [3]:
data

N   P   K  temperature   humidity        ph    rainfall   label
0      90  42  43    20.879744  82.002744  6.502985  202.935536    rice
1      85  58  41    21.770462  80.319644  7.038096  226.655537    rice
2      60  55  44    23.004459  82.320763  7.840207  263.964248    rice
3      74  35  40    26.491096  80.158363  6.980401  242.864034    rice
4      78  42  42    20.130175  81.604873  7.628473  262.717340    rice
...   ...  ..  ..          ...        ...       ...         ...     ...
2195  107  34  32    26.774637  66.413269  6.780064  177.774507  coffee
2196   99  15  27    27.417112  56.636362  6.086922  127.924610  coffee
2197  118  33  30    24.131797  67.225123  6.362608  173.322839  coffee
2198  117  32  34    26.272418  52.127394  6.758793  127.175293  coffee
2199  104  18  30    23.603016  60.396475  6.779833  140.937041  coffee

[2200 rows x 8 columns]

In [4]:
data.isnull().sum()

N              0
P              0
K              0
temperature    0
humidity       0
ph             0
rainfall       0
label          0
dtype: int64

In [5]:
data.shape

(2200, 8)

In [6]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2200 entries, 0 to 2199
Data columns (total 8 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   N            2200 non-null   int64  
 1   P            2200 non-null   int64  
 2   K            2200 non-null   int64  
 3   temperature  2200 non-null   float64
 4   humidity     2200 non-null   float64
 5   ph           2200 non-null   float64
 6   rainfall     2200 non-null   float64
 7   label        2200 non-null   object 
dtypes: float64(4), int64(3), object(1)
memory usage: 137.6+ KB


In [7]:
data.describe()

N            P            K  temperature     humidity  \
count  2200.000000  2200.000000  2200.000000  2200.000000  2200.000000   
mean     50.551818    53.362727    48.149091    25.616244    71.481779   
std      36.917334    32.985883    50.647931     5.063749    22.263812   
min       0.000000     5.000000     5.000000     8.825675    14.258040   
25%      21.000000    28.000000    20.000000    22.769375    60.261953   
50%      37.000000    51.000000    32.000000    25.598693    80.473146   
75%      84.250000    68.000000    49.000000    28.561654    89.948771   
max     140.000000   145.000000   205.000000    43.675493    99.981876   

                ph     rainfall  
count  2200.000000  2200.000000  
mean      6.469480   103.463655  
std       0.773938    54.958389  
min       3.504752    20.211267  
25%       5.971693    64.551686  
50%       6.425045    94.867624  
75%       6.923643   124.267508  
max       9.935091   298.560117

# Split independent variable and dependent variable

In [8]:
x=data.iloc[:,:-2].values
y=data.iloc[:,-1:].values

In [9]:
x

array([[ 90.        ,  42.        ,  43.        ,  20.87974371,
         82.00274423,   6.50298529],
       [ 85.        ,  58.        ,  41.        ,  21.77046169,
         80.31964408,   7.03809636],
       [ 60.        ,  55.        ,  44.        ,  23.00445915,
         82.3207629 ,   7.84020714],
       ...,
       [118.        ,  33.        ,  30.        ,  24.13179691,
         67.22512329,   6.36260785],
       [117.        ,  32.        ,  34.        ,  26.2724184 ,
         52.12739421,   6.75879255],
       [104.        ,  18.        ,  30.        ,  23.60301571,
         60.39647474,   6.77983261]])

In [10]:
y

array([['rice'],
       ['rice'],
       ['rice'],
       ...,
       ['coffee'],
       ['coffee'],
       ['coffee']], dtype=object)

# Feature Scaling

In [11]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y =  le.fit_transform(y)

C:\Users\HP\anaconda3\lib\site-packages\sklearn\utils\validation.py:63: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(*args, **kwargs)


In [12]:
y

array([20, 20, 20, ...,  5,  5,  5])

# Split train and test dataset

In [13]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y, test_size=0.2,random_state=0)

In [14]:
x_train

array([[ 27.        , 120.        , 200.        ,  21.45278675,
         90.74531921,   6.11021883],
       [ 81.        ,  36.        ,  38.        ,  23.76554749,
         87.98329901,   6.33483786],
       [ 90.        ,  59.        ,  35.        ,  24.25133493,
         89.86454053,   7.09822793],
       ...,
       [ 35.        ,  64.        ,  15.        ,  28.47442276,
         63.53604453,   6.50014496],
       [ 39.        ,  65.        ,  23.        ,  25.43459777,
         69.12613376,   7.6859593 ],
       [ 14.        ,  22.        ,   9.        ,  17.24944623,
         91.13772765,   6.54319181]])

In [15]:
x_test

array([[105.        ,  14.        ,  50.        ,  26.2148837 ,
         87.6883982 ,   6.41905219],
       [ 91.        ,  12.        ,  46.        ,  24.64458469,
         85.49938185,   6.34394252],
       [ 14.        , 121.        , 203.        ,   9.72445761,
         83.74765639,   6.15868941],
       ...,
       [117.        ,  56.        ,  15.        ,  25.99237426,
         77.0543546 ,   7.36825823],
       [ 27.        ,  64.        ,  21.        ,  32.84213012,
         68.68401492,   7.54380422],
       [ 31.        , 130.        , 198.        ,  21.80129837,
         92.73446667,   5.55482356]])

In [16]:
y_train

array([ 0,  8,  8, ...,  2, 10, 16])

In [17]:
y_test

array([21, 21,  7,  3,  2, 20, 13,  9, 15,  1, 13,  5, 10, 14, 12,  0,  5,
       10,  5, 12,  4,  2,  9,  8,  6,  5, 10, 16, 13,  9, 19, 20, 11, 15,
        4,  6, 12, 12, 21, 13, 11,  2, 18, 21, 18, 14,  9,  9,  6, 14, 13,
        2,  0, 15, 18,  1, 17, 12, 10,  6, 16, 14, 21, 20, 15,  0,  7,  5,
        0, 16,  4, 19,  9, 11,  7, 13,  3, 11,  8, 12, 20,  2, 21, 21, 15,
        6, 11, 10, 13, 17,  2,  8, 14,  7, 14, 11,  5,  8, 10,  3, 16,  8,
       14,  1,  1, 20, 21,  5, 18, 15, 15, 12,  5,  7, 16, 19, 14, 10, 11,
        8, 19, 10, 16,  3,  3,  2, 19, 16,  3, 17, 13, 13, 15, 14, 11, 14,
        4, 19, 16,  2,  2,  7,  0,  5,  3,  0,  8, 12, 21, 17, 16,  4, 13,
        1, 19,  3, 21,  2,  0,  8, 10, 18,  8,  9,  9, 15, 20, 15,  1, 16,
       18,  0, 13,  4,  6, 14,  9, 19, 17, 16, 20, 17, 17, 18,  9,  1,  4,
       18, 20, 17, 11,  8, 13, 20, 11,  5, 18,  4,  3, 12,  4, 19, 11, 13,
       13, 16, 15, 11, 18,  1,  3,  2, 18, 16, 13, 14, 12, 17, 15, 19, 20,
       20,  2, 17,  2,  5

# Random Forest Classifier Model

Train Model

In [42]:
from sklearn.ensemble import RandomForestClassifier
rfc=RandomForestClassifier(n_estimators=100,criterion='entropy')
rfc.fit(x_train,y_train)

RandomForestClassifier(criterion='entropy')

Test Model

In [43]:
pre_rfc=rfc.predict(x_test)

In [44]:
np.concatenate((y_test.reshape(len(y_test),1),pre_rfc.reshape(len(pre_rfc),1)),1)

array([[21, 21],
       [21, 21],
       [ 7,  7],
       [ 3,  3],
       [ 2,  2],
       [20,  8],
       [13, 13],
       [ 9,  9],
       [15, 15],
       [ 1,  1],
       [13, 13],
       [ 5,  5],
       [10, 10],
       [14, 14],
       [12, 12],
       [ 0,  0],
       [ 5,  5],
       [10, 10],
       [ 5,  5],
       [12, 12],
       [ 4,  4],
       [ 2,  2],
       [ 9,  9],
       [ 8,  8],
       [ 6,  6],
       [ 5,  5],
       [10, 10],
       [16, 16],
       [13, 13],
       [ 9,  9],
       [19, 19],
       [20, 20],
       [11, 11],
       [15, 15],
       [ 4,  4],
       [ 6,  6],
       [12, 12],
       [12, 12],
       [21, 21],
       [13,  2],
       [11, 11],
       [ 2,  2],
       [18, 18],
       [21, 21],
       [18, 18],
       [14, 14],
       [ 9,  9],
       [ 9,  9],
       [ 6,  6],
       [14, 14],
       [13, 13],
       [ 2,  2],
       [ 0,  0],
       [15, 15],
       [18, 18],
       [ 1,  1],
       [17, 17],
       [12, 12],
       [10, 10

In [45]:
cm = confusion_matrix(y_test, pre_rfc)
print(cm)
accuracy_score(y_test, pre_rfc)

[[18  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0 18  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0 19  0  0  0  0  0  0  0  3  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0 23  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0 15  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0 17  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0 16  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0 18  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0 19  0  0  0  0  0  0  0  0  0  0  0  2  0]
 [ 0  0  0  0  0  0  0  0  0 20  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  2  0  0  0  0  0  0  0 15  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0 18  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0 21  0  0  0  0  0  0  0  0  0]
 [ 0  0  1  0  0  0  0  0  0  0  0  0  0 21  0  0  0  0  3  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0

0.9613636363636363

In [47]:
pre_rfc=le.inverse_transform(pre_rfc)